language: c++
sudo: required
dist: bionic
services:
  - docker
env:
  global:
    - USE_TRAVIS=true
    - USE_DOCKER=true
    - ROS_PARALLEL_TEST_JOBS="-j8"
    - GIT_SSL_NO_VERIFY=1 # http://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c
  matrix:
    - CHECK_PYTHON3_COMPILE=true
    - ROS_DISTRO=indigo  USE_DEB=true
    - ROS_DISTRO=kinetic USE_DEB=true
    - ROS_DISTRO=kinetic USE_DEB=true DOCKER_IMAGE=i386/ubuntu:16.04
    - ROS_DISTRO=melodic USE_DEB=true
    - ROS_DISTRO=noetic  USE_DEB=true
    - ROS_DISTRO=noetic  USE_DEB=false
matrix:
  fast_finish: true
  allow_failures:
    - env: ROS_DISTRO=hydro   USE_DEB=true USE_DOCKER=true
    - env: ROS_DISTRO=noetic  USE_DEB=true
script:
  - if [ "${CHECK_PYTHON3_COMPILE}" == "true" ]; then python3 -m compileall .; exit $?; fi
  - source .travis/travis.sh
notifications:
  email:
    on_success: always
    on_failure: always
