#!/bin/bash -e

. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup

errmsg()
{
    echo >&2 ''
    echo >&2 "$@"
    echo >&2 "try 'dpkg-reconfigure debconf' to select a frontend other than noninteractive"
    echo >&2 ''
    exit 1
}

INSTALL_DIR=/opt/ros/indigo/share/julius

rm -rf $INSTALL_DIR/conf
rm -rf $INSTALL_DIR/model
rm -rf $INSTALL_DIR/SampleGrammars
rm -rf $INSTALL_DIR/SampleGrammars_en
